#!/usr/bin/env python3
"""
gen_setup_btree.py — Generates setup_btree_Nd.lp files for use with btree_constructor.lp

Each generated file contains one integrity constraint per valid decomposition vector,
selecting the correct btree/4 fact based on the clingcon constants v0..v(n-1).

Usage:
    python3 gen_setup_btree.py <n>        # generate setup_btree_Nd.lp
    python3 gen_setup_btree.py 3 4 5      # generate for multiple dimensions

The generated file is used as:
    clingcon N -c d=4 -c v0=0 -c v1=1 -c v2=2 -c v3=0 -c v4=0 \\
        setup_btree_4d.lp btree_constructor.lp
"""

import sys
from itertools import product as iproduct


def valid_vecs(n):
    """Enumerate all valid decomposition vectors for dimension n (unique, sorted)."""
    seen = set()
    # vec[i] = count of (n-i)-dimensional sub-dynamics, i in 0..n
    # constraint: sum_i vec[i] * 2^(n-i) = 2^n
    target = 2 ** n
    max_counts = [target // (2 ** (n - i)) for i in range(n + 1)]
    for counts in iproduct(*[range(mc + 1) for mc in max_counts]):
        total = sum(counts[i] * (2 ** (n - i)) for i in range(n + 1))
        if total == target:
            key = tuple(counts)
            if key not in seen:
                seen.add(key)
                yield list(counts)


def btree_term(vec, n):
    """Build the btree/4 term string for the given decomposition vector."""
    target = {}
    for i, cnt in enumerate(vec):
        d = n - i
        if cnt > 0 and d >= 1:
            target[d] = cnt

    def build(dim):
        if target.get(dim, 0) > 0:
            target[dim] -= 1
            return f"btree(nil,nil,{dim},nil)"
        if dim <= 0:
            return f"btree(nil,nil,{dim},nil)"
        left  = build(dim - 1)
        right = build(dim - 1)
        return f"btree({left},{right},{dim},nil)"

    return build(n)


def guards(vec, n):
    """
    Build guard conditions: vi = vec[i] for i in 0..n-1.
    Convention: vi corresponds to vec[n-1-i] (v0 = highest dim count).
    Following setup_decomp.lp: v0 is the leftmost (highest dim).
    """
    parts = []
    for vi_idx in range(n):
        vec_idx = n - 1 - vi_idx   # vi_idx=0 -> vec[n-1], vi_idx=1 -> vec[n-2], ...
        parts.append(f"v{vi_idx} = {vec[vec_idx]}")
    return ", ".join(parts)


def generate(n):
    lines = [
        f"% setup_btree_{n}d.lp",
        f"% Selects the correct btree/4 fact from the decomposition vector constants.",
        f"% Generated by gen_setup_btree.py",
        f"%",
        f"% Usage:",
        f"%   clingcon N -c d={n} -c v0=X ... -c v{n}=Y \\",
        f"%       setup_btree_{n}d.lp btree_constructor.lp",
        f"",
        f"#const d = {n}.",
    ]
    for i in range(n):
        lines.append(f"#const v{i} = 0.")
    lines.append(f"#const v{n} = 1.")
    lines.append("")

    vecs = list(valid_vecs(n))
    lines.append(f"% {len(vecs)} valid decomposition vectors for d={n}")
    lines.append("")

    for vec in vecs:
        term  = btree_term(vec, n)
        guard = guards(vec, n+1)
        vec_str = ",".join(map(str, vec))
        lines.append(f"% vec = <{vec_str}>")
        lines.append(f"{term} :- {guard}.")
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    dims = [int(x) for x in sys.argv[1:]] if len(sys.argv) > 1 else [3, 4]
    for n in dims:
        content = generate(n)
        fname = f"setup_btree_{n}d.lp"
        with open(f"./{fname}", "w") as f:
            f.write(content)
        vcount = len(list(valid_vecs(n)))
        print(f"Generated {fname} ({vcount} cases)")
